name: Release

on:
  workflow_dispatch: # Manual triggering to re-run a release with a different run_number  
  push:
    branches:
    - 'release'

env:
  release_tag: v1.0.0-alpha.${{ github.run_number }}


jobs:
  docker-build-and-push:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        package: [auth, backend, frontend]
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/rafiki-${{ matrix.package }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: packages/${{ matrix.package }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  tag-and-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          name: "Rafiki ${{ env.release_tag }}"
          tag_name: ${{ env.release_tag }}
          generate_release_notes: true