name: Release

on:
  workflow_dispatch: # Manual triggering to re-run a release with a different run_number  
  push:
    branches:
    - 'release'

env:
  release_tag: v1.0.0-alpha.${{ github.run_number }}


jobs:
  docker-build-and-push:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        package: [auth, backend, frontend]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: latest, $release_tag
          file: packages/${{ matrix.package }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  tag-and-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.release_tag }}',
              sha: context.sha
            })

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          name: "Rafiki $release_tag"
          tag_name: $release_tag
          generate_release_notes: true